apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev-frontend
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: frontend