apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yml
  - nginx/ingress.yml

images:
  - name: prod-backend
    newName: <ECR_URL>/backend
    newTag: "v1"
  - name: prod-frontend
    newName: <ECR_URL>/frontend
    newTag: "v1"

patches:
  - target:
      kind: Deployment
      name: backend-deployment
      namespace: prod-backend
    path: backend/deployment-patch.yml
  - target:
      kind: Service
      name: backend-service
      namespace: prod-backend
    path: backend/service-patch.yml
  - target:
      kind: Ingress
      name: nginx-ingress
      namespace: prod-ingress
    path: nginx/ingress.yml